#!/bin/bash

# Создать в директории для совместной работы поддиректорию для обмена файлами,
# но чтобы удалять файлы могли только их создатели.

mkdir new_directory
cd new_directory
mkdir shared
chmod ug+rwx shared
chmod o+rx shared
chmod =t shared/
