#!/bin/bash

# Дать созданным файлам другие, произвольные имена.
# Создать новую символическую ссылку. Переместить ссылки в другую директорию.

mv file1 crazy
mv file2 angry

ln -s crazy angry_01

mkdir test
mv angry_01 bird ./test/
